"""Contratos estruturais dos repositórios de memória e Firestore."""
from typing import Protocol, TypeVar
from app.schemas.agendamentos import AgendamentoResponse
from app.schemas.horarios import HorarioResponse

T = TypeVar("T")


class CatalogRepository(Protocol[T]):
    def create(self, **payload) -> T: ...
    def list(self) -> list[T]: ...
    def get_by_id(self, document_id: str) -> T | None: ...


class HorarioDataRepository(Protocol):
    def create(self, profissionalId: str, clinicaId: str, data: str, hora: str,
               disponivel: bool) -> HorarioResponse: ...
    def list(self, profissionalId: str | None = None, data: str | None = None,
             disponivel: bool | None = None) -> list[HorarioResponse]: ...


class AgendamentoDataRepository(Protocol):
    def create(self, pacienteId: str, horarioId: str) -> AgendamentoResponse: ...
    def list(self, pacienteId: str | None = None) -> list[AgendamentoResponse]: ...
    def get_by_id(self, agendamento_id: str) -> AgendamentoResponse | None: ...
    def cancel(self, agendamento_id: str) -> AgendamentoResponse: ...
    def reschedule(self, agendamento_id: str, novoHorarioId: str) -> AgendamentoResponse: ...
